# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9859fe6f9c1880b646a30efcc41e068cdee60d8ac3890d95b54e707b55670739e0b5687faf06bae770bd4ded7c1800b49c16b6d85d245ca7a6889635359cc81b

test:
  secret_key_base: bc7659db90ec6247cec5b16f0090dab3df60976e58b0120a3b7d0e45e021c463907a0d6073b06d681d0524f75ba0c28d84df65b1a1779eaaa8b9e679005204ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
